### ISSUE TITLE
Вопросы по учебному материалу

### ISSUE THREAD

**Issue by imagency** [yzh44yzh/practical_erlang#1]
Добрый день, Юрий!
1) Скажите, строка 36 в файле:
https://github.com/yzh44yzh/practical_erlang/blob/master/02_list_recursion/solution/task_1.erl
лишняя, я правильно понимаю?
2) https://github.com/yzh44yzh/practical_erlang/blob/master/04_pattern_matching/lesson_04.md
area({rect, Width, Height}) -> Width * Height;
area({square, Size}) -> Size * Size;
area({circle, Radius}) -> math:pi() * Radius * Radius.
Тут разве не точка после первого клоуза должна быть, 
area({rect, Width, Height}) -> Width * Height.
учитывая, что функция с отличным числом аргументов?

Спасибо за труд!

**Comment by yzh44yzh** [comment]
Привет
1) да, эта строка лишняя
2) нет, тут функция с одним аргументом. Этим одним аргументом могут быть кортежи разного размера, но аргумент все равно один.

**Comment by imagency** [comment]
2) А, точно! Спасибо!
