### ISSUE TITLE
some function deprecated

### ISSUE THREAD

**Issue by sergeydru** [yzh44yzh/practical_erlang#6]
short_link.erl:9: Warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
short_link.erl:10: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead

**Comment by yzh44yzh** [comment]
ok, thanks

**Comment by yzh44yzh** [comment]
No need to close this issue. I didn't fix it yet )

**Comment by sergeydru** [comment]
sorry )) will post here if find something else
